[package]
name = "chip8"
version = "0.1.0"
authors = ["Paul Mannino <pmannino.code@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
crate-type = ["cdylib"]

[dependencies]
rand = { version = "0.7.3", features = ["wasm-bindgen"] }
wasm-bindgen = "0.2.64"
console_error_panic_hook = "0.1.6"
